## This is a heading

This is some normal text.


```{Mathematica}
var = 10
Do[var = var + 1, {10}];
(* var == 20! *)
var = "foo";
var

Print["This is some mathematica code."];
Range[10]
```

## This is another heading

And even more text.

```{Mathematica}
Print["Some more code."];
var
```

## Third heading
Bye bye!
